### ISSUE TITLE
Reconnect not working properly

### ISSUE THREAD

**Issue by markose** [bit4bit/gami#1]
Hello,

thank you for the AMI Adapter, it's great work.
Though it seems that there are two small issues with the reconnect machanism you provide. Please have a look at the following code snippets. I commented two lines with '!!!!!'

it seems that your reconnect does not work properly as there is a race condition in your example code:
###### 

func (client *AMIClient) Reconnect() error {
    client.conn.Close()
    reconnect, err := Dial(client.address)

```
if err != nil {
    //client.NetError <- err  <--- !!!!!! Do not pass the error to the channel, because it blocks
    return err
}

//new connection
client.conn = reconnect.conn
client.connRaw = reconnect.connRaw
client.waitNewConnection <- struct{}{}

if err := client.Login(client.amiUser, client.amiPass); err != nil {
    return err
}

return nil
```

}
###### 

//install manager
    go func() {
        for {
            select {
            //handle network errors
            case err := <-ami.NetError:
                log.Println("Network Error:", err)
                //try new connection every second
                for {
                    <-time.After(time.Second)
                    if err := ami.Reconnect(); err == nil {
                        //call start actions
                        if _, err := ami.Action("Events", gami.Params{"EventMask": "on"}); err != nil { // <--- !!!!!! This should break if 'err == nil' --> Seems to be a typo
                            break
                        }
                    }
                }

```
        case err := <-ami.Error:
            log.Println("error:", err)
        //wait events and process
        case ev := <-ami.Events:
            log.Println("Event Detect: %v", *ev)
            //if want type of events
            log.Println("EventType:", event.New(ev))
        }
    }
}()
```

Regards,
Marko

**Comment by bit4bit** [comment]
uuu thanks i see the race, that for {} it's not need, we can let main for to handle reconnection

gracias
