### ISSUE TITLE
Data race when concurrently accessing client.response map in notifyResponse func.

### ISSUE THREAD

**Issue by gborisov** [bit4bit/gami#4]
Hello, 
data race conditions were detected when concurrently performing actions, presumably, due to read locks in notifyResponse method, which not only performs read ops but also a write operation on the map (delete). Would you consider fixing this (e.g. using a full lock instead or something)?
Thanks.

`==================
WARNING: DATA RACE
Read at 0x00c42001b740 by goroutine 62:
  runtime.mapaccess1_faststr()
      /usr/local/go/src/runtime/hashmap_fast.go:192 +0x0
  github.com/bit4bit/gami.(*AMIClient).notifyResponse.func1()
      .../src/github.com/bit4bit/gami/gami.go:273 +0xb9

Previous write at 0x00c42001b740 by goroutine 95:
  runtime.mapdelete()
      /usr/local/go/src/runtime/hashmap.go:558 +0x0
  github.com/bit4bit/gami.(*AMIClient).notifyResponse.func1()
      .../src/github.com/bit4bit/gami/gami.go:275 +0x1b3

Goroutine 62 (running) created at:
  github.com/bit4bit/gami.(*AMIClient).notifyResponse()
      .../src/github.com/bit4bit/gami/gami.go:277 +0x56
  github.com/bit4bit/gami.(*AMIClient).Run.func1()
      .../src/github.com/bit4bit/gami/gami.go:257 +0x3c4

Goroutine 95 (finished) created at:
  github.com/bit4bit/gami.(*AMIClient).notifyResponse()
      .../src/github.com/bit4bit/gami/gami.go:277 +0x56
  github.com/bit4bit/gami.(*AMIClient).Run.func1()
      .../src/github.com/bit4bit/gami/gami.go:257 +0x3c4
==================`

**Comment by bit4bit** [comment]
thanks.
i not used full lock, because we can't know if they client are listen for the chan action.
